import './globals.css';
import { Inter } from 'next/font/google';
import Header from '@/components/header';
import { User } from '@/models/user';
import ChatV2 from '@/components/chatv2';
import { WebSocketProvider } from '@/context/wsContext';
import { ChatContextProvider } from '@/context/chatContext';
import { SessionContextProvider } from '@/context/sessionContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
  initialSession: User | null;
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className} overflow-x-hidden`}>
        <SessionContextProvider>
          <WebSocketProvider>
            <ChatContextProvider>
              <Header></Header>
              <ChatV2></ChatV2>
              {children}
            </ChatContextProvider>
          </WebSocketProvider>
        </SessionContextProvider>
      </body>
    </html>
  );
}
